import type {
  Appointment,
  BlockedTime,
  BookingSettings,
  BusinessHour,
  BusinessSettings,
  Customer,
  GalleryItem,
  Offer,
  Service,
  ServiceCategory,
} from '../types/domain'

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`

export const siteOptions = {
  enableVisitInfoSection: true,
}

export const businessSettings: BusinessSettings = {
  salonName: 'Vishal Mens Parlour',
  tagline: 'Premium men’s grooming in Gorakhpur',
  phone: '+91 9456 7890',
  whatsapp: '+91 9456 7890',
  email: 'hello@vishalmensparlour.in',
  address: 'Golghar Market, Gorakhpur',
  landmark: 'Near City Mall',
  city: 'Gorakhpur',
  state: 'Uttar Pradesh',
  pinCode: '273001',
  mapsUrl: 'https://maps.google.com/?q=Golghar%20Gorakhpur',
  timezone: 'Asia/Kolkata',
  currency: 'INR',
  heroImage: '/media/home-hero-barbershop.png',
  shopImage: '/media/home-hero-barbershop.png',
  galleryHeroImage: img('photo-1512690459411-b9245aed614b'),
  servicesHeroImage: img('photo-1621605815971-fbc98d665033'),
}

export const categories: ServiceCategory[] = [
  {
    id: 'haircuts',
    name: 'Haircuts',
    slug: 'haircuts',
    description: 'Precision cuts tailored to your face shape and lifestyle.',
    imagePath: img('photo-1599351431202-1e0f0137899a'),
    displayOrder: 1,
  },
  {
    id: 'beard-shave',
    name: 'Beard & Shave',
    slug: 'beard-shave',
    description: 'Traditional shaves, sculpting, and beard care rituals.',
    imagePath: img('photo-1503951914875-452162b0f3f1'),
    displayOrder: 2,
  },
  {
    id: 'hair-colour',
    name: 'Hair Colour',
    slug: 'hair-colour',
    description: 'Subtle coverage, highlights, and confident colour refreshes.',
    imagePath: img('photo-1622296089863-eb7fc530daa8'),
    displayOrder: 3,
  },
  {
    id: 'facial-skin',
    name: 'Facial & Skin Care',
    slug: 'facial-skin-care',
    description: 'Rejuvenating skin care designed for men.',
    imagePath: img('photo-1616394584738-fc6e612e71b9'),
    displayOrder: 4,
  },
  {
    id: 'treatments',
    name: 'Hair Treatment',
    slug: 'hair-treatment',
    description: 'Targeted care for scalp health, texture, and shine.',
    imagePath: img('photo-1559599101-f09722fb4948'),
    displayOrder: 5,
  },
  {
    id: 'packages',
    name: 'Grooming Packages',
    slug: 'grooming-packages',
    description: 'Complete services for weddings, events, and monthly upkeep.',
    imagePath: img('photo-1585747860715-2ba37e788b70'),
    displayOrder: 6,
  },
]

export const services: Service[] = [
  {
    id: 'classic-haircut',
    name: 'Classic Haircut',
    slug: 'classic-haircut',
    categoryId: 'haircuts',
    shortDescription: 'Traditional scissor or clipper cut, tailored to your style.',
    description: 'Consultation, wash, cut, and clean finish for everyday grooming.',
    price: 300,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 30,
    imagePath: img('photo-1599351431202-1e0f0137899a'),
    featured: true,
    bookable: true,
    active: true,
    displayOrder: 1,
  },
  {
    id: 'premium-haircut',
    name: 'Premium Haircut',
    slug: 'premium-haircut',
    categoryId: 'haircuts',
    shortDescription: 'Detailed cut with shampoo, blow dry, and premium styling.',
    description: 'A full grooming cut with consultation and finishing product.',
    price: 500,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 45,
    imagePath: img('photo-1621605815971-fbc98d665033'),
    featured: true,
    bookable: true,
    active: true,
    displayOrder: 2,
  },
  {
    id: 'fade-style-cut',
    name: 'Fade / Style Cut',
    slug: 'fade-style-cut',
    categoryId: 'haircuts',
    shortDescription: 'Precision fading techniques for a sharp modern finish.',
    description: 'Skin fade, taper, or custom style shaped with detail.',
    price: 400,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 45,
    imagePath: img('photo-1622296089863-eb7fc530daa8'),
    featured: false,
    bookable: true,
    active: true,
    displayOrder: 3,
  },
  {
    id: 'hot-towel-shave',
    name: 'Hot Towel Shave',
    slug: 'hot-towel-shave',
    categoryId: 'beard-shave',
    shortDescription: 'Traditional straight razor shave with hot towel and balm.',
    description: 'Pre-shave oil, warm towel, straight razor shave, and soothing finish.',
    price: 350,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 30,
    imagePath: img('photo-1503951914875-452162b0f3f1'),
    featured: true,
    bookable: true,
    active: true,
    displayOrder: 4,
  },
  {
    id: 'beard-sculpting',
    name: 'Beard Sculpting',
    slug: 'beard-sculpting',
    categoryId: 'beard-shave',
    shortDescription: 'Expert shaping and trimming to complement your face.',
    description: 'Line-up, trim, conditioning, and beard oil finish.',
    price: 250,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 25,
    imagePath: img('photo-1512690459411-b9245aed614b'),
    featured: false,
    bookable: true,
    active: true,
    displayOrder: 5,
  },
  {
    id: 'detox-facial',
    name: 'Detox Facial',
    slug: 'detox-facial',
    categoryId: 'facial-skin',
    shortDescription: 'Deep cleansing facial to remove impurities and hydrate skin.',
    description: 'Cleanse, exfoliation, mask, serum, and massage.',
    price: 600,
    discountPrice: null,
    pricingType: 'FIXED',
    durationMinutes: 45,
    imagePath: img('photo-1616394584738-fc6e612e71b9'),
    featured: true,
    bookable: true,
    active: true,
    displayOrder: 6,
  },
  {
    id: 'global-hair-colour',
    name: 'Global Hair Colour',
    slug: 'global-hair-colour',
    categoryId: 'hair-colour',
    shortDescription: 'Premium colour application for a complete style refresh.',
    description: 'Consultation, colour application, rinse, and styling.',
    price: 900,
    discountPrice: null,
    pricingType: 'STARTING_FROM',
    durationMinutes: 90,
    imagePath: img('photo-1560066984-138dadb4c035'),
    featured: false,
    bookable: true,
    active: true,
    displayOrder: 7,
  },
  {
    id: 'complete-grooming',
    name: 'The Complete Grooming Experience',
    slug: 'complete-grooming-experience',
    categoryId: 'packages',
    shortDescription: 'Haircut, beard trim, styling, detox facial, and head massage.',
    description: 'The signature package for weddings, interviews, and special days.',
    price: 1200,
    discountPrice: 899,
    pricingType: 'FIXED',
    durationMinutes: 120,
    imagePath: img('photo-1585747860715-2ba37e788b70'),
    featured: true,
    bookable: true,
    active: true,
    displayOrder: 8,
  },
]

export const offers: Offer[] = [
  {
    id: 'complete-grooming',
    title: 'The Complete Grooming Experience',
    description: 'Haircut, beard trim, styling, detox facial, and relaxing head massage.',
    originalPrice: 1200,
    offerPrice: 899,
    active: true,
    featured: true,
  },
  {
    id: 'father-son',
    title: 'Father & Son Combo',
    description: 'Two premium haircuts for a sharp family visit.',
    originalPrice: 700,
    offerPrice: 600,
    active: true,
    featured: false,
  },
]

export const galleryItems: GalleryItem[] = [
  {
    id: 'g1',
    category: 'Haircut',
    caption: 'Sharp textured crop with clean sides',
    imagePath: img('photo-1599351431202-1e0f0137899a'),
    thumbnailPath: img('photo-1599351431202-1e0f0137899a'),
    featured: true,
    visible: true,
  },
  {
    id: 'g2',
    category: 'Beard & Shave',
    caption: 'Relaxed hot towel shave',
    imagePath: img('photo-1503951914875-452162b0f3f1'),
    thumbnailPath: img('photo-1503951914875-452162b0f3f1'),
    featured: true,
    visible: true,
  },
  {
    id: 'g3',
    category: 'Salon Interior',
    caption: 'Warm traditional parlour interior',
    imagePath: img('photo-1585747860715-2ba37e788b70'),
    thumbnailPath: img('photo-1585747860715-2ba37e788b70'),
    featured: true,
    visible: true,
  },
  {
    id: 'g4',
    category: 'Styling',
    caption: 'Detailed beard line and finish',
    imagePath: img('photo-1512690459411-b9245aed614b'),
    thumbnailPath: img('photo-1512690459411-b9245aed614b'),
    featured: false,
    visible: true,
  },
  {
    id: 'g5',
    category: 'Hair Colour',
    caption: 'Confident colour refresh',
    imagePath: img('photo-1560066984-138dadb4c035'),
    thumbnailPath: img('photo-1560066984-138dadb4c035'),
    featured: false,
    visible: true,
  },
  {
    id: 'g6',
    category: 'Facial',
    caption: 'Skin care and grooming session',
    imagePath: img('photo-1616394584738-fc6e612e71b9'),
    thumbnailPath: img('photo-1616394584738-fc6e612e71b9'),
    featured: false,
    visible: true,
  },
]

export const businessHours: BusinessHour[] = [1, 2, 3, 4, 5, 6].map((weekday) => ({
  weekday,
  isOpen: true,
  opensAt: '09:00',
  closesAt: '21:00',
}))

businessHours.push({ weekday: 0, isOpen: false, opensAt: '00:00', closesAt: '00:00' })

export const bookingSettings: BookingSettings = {
  bookingEnabled: true,
  otpRequired: true,
  advanceBookingDays: 21,
  minimumNoticeMinutes: 60,
  slotIntervalMinutes: 30,
}

export const blockedTimes: BlockedTime[] = [
  {
    id: 'lunch',
    startAt: '2026-09-02T13:00:00+05:30',
    endAt: '2026-09-02T13:30:00+05:30',
    reason: 'Lunch break',
  },
]

export const appointments: Appointment[] = [
  {
    id: 'a1',
    bookingReference: 'VMP-2401',
    customerName: 'Amit Rahul',
    customerPhone: '+919876543210',
    serviceName: 'Premium Haircut',
    serviceId: 'premium-haircut',
    staffName: 'Vishal',
    startAt: '2026-09-02T10:30:00+05:30',
    endAt: '2026-09-02T11:15:00+05:30',
    status: 'CONFIRMED',
    servicePriceSnapshot: 500,
  },
  {
    id: 'a2',
    bookingReference: 'VMP-2402',
    customerName: 'Vikram Singh',
    customerPhone: '+919999888877',
    serviceName: 'Hot Towel Shave',
    serviceId: 'hot-towel-shave',
    staffName: 'Alex',
    startAt: '2026-09-02T11:30:00+05:30',
    endAt: '2026-09-02T12:00:00+05:30',
    status: 'PENDING',
    servicePriceSnapshot: 350,
  },
  {
    id: 'a3',
    bookingReference: 'VMP-2403',
    customerName: 'John Doe',
    customerPhone: '+919812345678',
    serviceName: 'Classic Haircut',
    serviceId: 'classic-haircut',
    staffName: 'Vishal',
    startAt: '2026-09-02T15:00:00+05:30',
    endAt: '2026-09-02T15:30:00+05:30',
    status: 'COMPLETED',
    servicePriceSnapshot: 300,
  },
]

export const customers: Customer[] = [
  {
    id: 'c1',
    name: 'Amit Rahul',
    phone: '+919876543210',
    email: 'amit@example.com',
    firstVisit: '2026-08-08',
    lastVisit: '2026-09-02',
    appointmentCount: 5,
  },
  {
    id: 'c2',
    name: 'Vikram Singh',
    phone: '+919999888877',
    firstVisit: '2026-08-29',
    lastVisit: '2026-09-02',
    appointmentCount: 2,
  },
]
